services:
  - type: web
    name: frefire-bot-backend
    env: node
    buildCommand: npm ci --production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: "20"
    healthCheckPath: /api/bot/health
    autoDeploy: true 