services:
  - type: web
    name: frefire-bot-backend
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: "20"
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "false"
      - key: PUPPETEER_CACHE_DIR
        value: "/opt/render/project/src/node_modules/.cache/puppeteer"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/opt/render/project/src/node_modules/.cache/puppeteer/chrome-linux-*/chrome-linux/chrome"
      - key: PUPPETEER_DEBUG
        value: "true"
    healthCheckPath: /api/bot/health
    autoDeploy: true 
